### ISSUE TITLE
Issue with caps lock

### ISSUE THREAD

**Issue by Stefan2142** [madslundt/keybindings#1]
First, thanks for this a lot! I find it really useful. I found a problem with using the windows version (im using ijkl.ahk and pgUpPgDown.ahk scripts - i just double click on them to run them). The issue with PageUp/PageDown is that capslock stays on after pressing caps+y/h and then to turn off caps locks, I have to again press caps+y/h. Is there a way to fix it?

**Comment by madslundt** [comment]
The only way I could get it to work was to include pgUp and pgDn into the ijkl.ahk script. So just ignore pgUpPgDown.ahk script for now and run the ijkl.ahk script.

I'll see if I can get it to work in pgUpPgDown.ahk
