### ISSUE TITLE
It doesn't work system-wide

### ISSUE THREAD

**Issue by kuator** [madslundt/keybindings#3]
```
❯ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19
DISTRIB_CODENAME=tara
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"
```
When I press caps-lock and i,j,k,l in menu it just print ijkl, but I want it to move cursor. I am using autokey.

**Comment by madslundt** [comment]
Did you map caps lock to be your hyper key instead of caps lock?

**Comment by kuator** [comment]
Yes, I mapped it to hyper in settings.

**Comment by madslundt** [comment]
What version of autokey are you using?
Do you have issues when assigning your own key bindings to autokey? If so it could look like a problem with autokey in Linux Mint 19.

**Comment by kuator** [comment]
It works in other applications except launcher. When try to press caps with j to move, it just prints j

**Comment by madslundt** [comment]
Did you try running autokey as root?

**Comment by kuator** [comment]
Actually, I removed Autokey, and started reading xkb documentation. Sorry for wasting your time

**Comment by yash-fn** [comment]
actually my issue might be a duplicate of this. Similarly my hotkey isn't appearing to work system wide either when I attempt to use it for GUI navigation.
